add event-model and event_type-mode
naist-sushi/sushi-library pull request #34
Opened 2021-02-05 06:10 UTC by eedy8888

2021-02-05 06:14 UTC, chez-shanpu commented
Models should be defined in `models.py`
Like this: https://docs.djangoproject.com/ja/3.1/intro/overview/#design-your-model

2021-02-05 06:20 UTC, chez-shanpu requested changes
https://github.com/naist-sushi/sushi-library/pull/34#issuecomment-773817369

And rebase or merge latest master branch

2021-02-05 07:18 UTC, eedy8888 commented
I fix it, please check it, thanks.

2021-02-05 07:20 UTC, eedy8888 commented
@chez-shanpu  I fix it, please check it, thanks.

2021-02-05 07:31 UTC, chez-shanpu requested changes
@eedy8888 please resolve conflicts

2021-02-05 07:53 UTC, eedy8888 commented
@chez-shanpu  please check it again, thanks.

2021-02-05 08:24 UTC, chez-shanpu requested changes
Please check my review.
And next time, please request a review after the 'check' has passed.
Thanks.

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
No need.

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +    )
Use `models.ForeignKey`

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +
Add foreign-key of `Book` and `User`, and `created_at`

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +    title = models.CharField(max_length=200)
What is title?

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +    )
No need.

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +
Too many empty lines.

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +    requested_date = models.DateField(null=True, blank=True)
No need.

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +        choices=EVENT_STATUS,
No need.

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +        max_length=10,
`max_length=255`

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +        help_text='Book availability',
No need.

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +    )
No need.

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +class event(models.Model):
Add Meta class and set `db_table`

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +        ordering = ['requested_date']
Put Meta class on the next line after `class event_type (models.Model):`.
`ordering` is not needed.
`db_table` is needed.

2021-02-05 08:24 UTC, chez-shanpu commented on sushi_library/library/models.py
> +
Too many lines.

2021-02-12 06:51 UTC, chez-shanpu commented
Working on it in #38.
So, I'll close this.

2021-02-12 06:51 UTC, closed without merging